'use client';

import './globals.css';
import { TopMenu } from '@/components/top-menu/top-menu';
import { LeftMenu } from '@/components/left-menu/left-menu';
import { DevSupport } from '@react-buddy/ide-toolbox-next';
import { ComponentPreviews, useInitial } from '@/dev';
import { regularTextFont } from '@/utils/fonts';

const font = regularTextFont;

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <body className={font.className}>
        <DevSupport ComponentPreviews={ComponentPreviews} useInitialHook={useInitial}>
            <section className="left-menu-container">
                <LeftMenu />
            </section>
            <section className="content-container">
                <TopMenu />
                <section>
                    {children}
                </section>
            </section>
        </DevSupport>
        </body>
        </html>
    );
}
