import './globals.css'
import { Comfortaa } from 'next/font/google'
import { TopMenu } from "@/components/top-menu/top-menu";
import { LeftMenu } from "@/components/left-menu/left-menu";

const font = Comfortaa({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <body className={font.className}>
        <section className="left-menu-container">
            <LeftMenu />
        </section>
        <section className="content-container">
            <TopMenu />
            <section>
                {children}
            </section>
        </section>
        </body>
        </html>
    )
}
