// That file was generated by src/scripts/generated-routes.js run it again to update
export const ROUTE_INDEX = "/";
export const ROUTE_ABOUT_ME = "/about-me";
export const ROUTE_CV_GENERATOR = "/cv-generator";